[forest]
trees = ["trees"]                   # The directories in which your trees are stored
assets = ["assets"]                  # The directories in which your assets are stored
theme = "themes"                      # The directory in which your theme is stored
