name: Deploy Static Page to GitHub Pages

on:
  push:
    branches:
      - main # Change this to the branch you want to deploy from (e.g., master, development)

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows the workflow to write to the gh-pages branch
      pages: write # Allows the workflow to deploy to GitHub Pages
      id-token: write # Required for OIDC authentication

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup OCaml and Opam
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 'ocaml-base-compiler.5.2.0' # You can specify your desired OCaml version
      - name: Install Forester and Build Site
        # Combine these steps so that `eval $(opam env)` persists for the commands
        run: |
          # Exit immediately if a command exits with a non-zero status
          # This helps catch errors early in the script
          set -euxo pipefail

          # Load Opam environment for this specific run block
          # This sets up the PATH so `opam` and `forester` can be found
          eval "$(opam env)"

          echo "Current PATH after opam env:"
          echo "$PATH" # Print the PATH to verify for debugging

          # Install Forester
          echo "Installing Forester..."
          opam install forester

          # Verify Forester installation by checking if the command exists
          # `which` returns the path to the executable or fails if not found
          echo "Verifying Forester command availability..."
          which forester || { echo "ERROR: 'forester' command not found after opam install!"; exit 1; }

          # You can also try running a simple forester command to confirm it works
          # forester --version # Uncomment if you want to see its version during the run

          # Build with Forester
          echo "Building site with Forester..."
          forester build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './output'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4